name: Matrix Workflow Example

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite execução manual

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Gerar matriz JSON
        id: set-matrix
        run: echo 'matrix={"include":[{"name":"Sucesso","value":1},{"name":"Erro","value":2}]}' >> $GITHUB_OUTPUT

  use-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Executando job da matriz
        run: |
          echo "Rodando ${{ matrix.name }} com valor ${{ matrix.value }}"
          if [ "${{ matrix.value }}" -eq 2 ]; then
            echo "Simulando erro..."
            exit 1
          fi

  final-step:
    needs: use-matrix
    runs-on: ubuntu-latest
    if: success()  # Agora só executa se todos os jobs de "use-matrix" forem bem-sucedidos
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Passo final usando a matriz
        run: echo "Finalizando ${{ matrix.name }} com valor ${{ matrix.value }}"
